// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xeuewjqontwjoascymly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhldWV3anFvbnR3am9hc2N5bWx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NjU0OTQsImV4cCI6MjA1NjE0MTQ5NH0.mCSTghdro8aXEbRLdAnBUl0jEOY5IMS8M6GE992XaRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);